# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Yannick Dayer <yannick.dayer@idiap.ch>

# SPDX-License-Identifier: BSD-3-Clause

# Inspired from https://github.com/readthedocs/actions/tree/v1/preview

name: Documentation preview on readthedocs for Pull Requests

on:
  pull_request_target:
    branches:
      [ "main" ]
    types:
      - opened
    paths:
      - "docs/**"
      - "src/**"  # Update to the Python API pages
      - ".github/workflows/doc-preview.yaml"

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-22.04
    steps:
      - name: Modify the PR with a link to the new docs
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: "clapper"
